spring.application.name=customer-relations-service
server.port=8084
spring.kafka.bootstrap-servers=localhost:9092

# MailHog (IntelliJ / host mode)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false